Repository aukilabs/posemesh, pull requests merged in 2024-11, with the labels that each got.

#12 feature: add send message APIs
  networking/include/Posemesh/Networking/API.h
  networking/src/context.rs
  networking/src/lib.rs
  sdk/include/Posemesh/C/Posemesh.h
  sdk/include/Posemesh/Posemesh.hpp
  sdk/platform/Apple/include/Posemesh/Posemesh.h
  sdk/platform/Apple/src/Posemesh.mm
  sdk/platform/Web/Posemesh.js
  sdk/platform/Web/src/Posemesh.cpp
  sdk/src/C/Posemesh.cpp
  sdk/src/Posemesh.cpp
Labels: enhancement

#15 feature: various improvements
  networking/include/Posemesh/Networking/API.h
  networking/src/context.rs
  sdk/CMakeLists.txt
  sdk/cmake/Platform.cmake
  sdk/cmake/SetAppleInfo.cmake
  sdk/include/Posemesh/C/Config.h
  sdk/include/Posemesh/C/Posemesh.h
  sdk/include/Posemesh/Config.hpp
  sdk/include/Posemesh/Posemesh.hpp
  sdk/platform/Apple/Info.plist.in
  sdk/platform/Apple/include/Posemesh/Config.h
  sdk/platform/Apple/include/Posemesh/Posemesh.h
  sdk/platform/Apple/src/Config.mm
  sdk/platform/Apple/src/Config.swift
  sdk/platform/Apple/src/Posemesh.mm
  sdk/platform/Web/Config.js
  sdk/platform/Web/Posemesh.js
  sdk/platform/Web/src/Config.cpp
  sdk/src/C/Config.cpp
  sdk/src/C/Posemesh.cpp
  sdk/src/Config.cpp
  sdk/src/Posemesh.cpp
Labels: enhancement

#16 chore: added build instructions to README
  sdk/README.md
Labels: documentation

#17 feature: add CI/CD
  .github/workflows/posemesh-sdk.yml
  .gitmodules
  networking/build.rs
  networking/include/Posemesh/Networking/API.h
  networking/src/lib.rs
  sdk/CMakeLists.txt
  sdk/cmake/GetCommitId.cmake
  sdk/cmake/MergeFiles.cmake
  sdk/cmake/TransformTypeScriptDefinitions.cmake
  sdk/include/Posemesh/C/Posemesh.h
  sdk/include/Posemesh/Posemesh.hpp
  sdk/platform/Apple/Info.plist.in
  sdk/platform/Apple/include/Posemesh/Posemesh.h
  sdk/platform/Apple/src/Posemesh.mm
  sdk/platform/Web/Posemesh.js
  sdk/platform/Web/VerifyCommitId.js.in
  sdk/platform/Web/src/Posemesh.cpp
  sdk/platform/Web/transform-typescript-definitions.js
  sdk/scripts/Build-Library.ps1
  sdk/scripts/Bundle-Framework.ps1
  sdk/scripts/Get-Version.ps1
  sdk/src/C/Posemesh.cpp
  sdk/src/Posemesh.cpp
Labels: enhancement

#20 feat: [PI-473] add set_stream_handler method to add custom stream handler
  networking/examples/private_dialer.rs
  networking/examples/private_receiver.rs
  networking/examples/relay.rs
  networking/src/client.rs
  networking/src/context.rs
  networking/src/network.rs
Labels: enhancement

#19 fix: [PI-497][PI-491] sending messages get stuck
  networking/Cargo.toml
  networking/examples/autonat_client.rs
  networking/examples/private_dialer.rs
  networking/examples/private_receiver.rs
  networking/examples/relay.rs
  networking/src/client.rs
  networking/src/context.rs
  networking/src/event.rs
  networking/src/network.rs
Labels: bug
