Repository aukilabs/posemesh, pull requests merged in 2025-03, with the labels that each got.

#45 chore: refactor networking
  core/Cargo.lock
  core/Cargo.toml
  core/base/Cargo.toml
  core/domain/Cargo.toml
  core/domain/examples/browser/main.js
  core/domain/src/binding_helper.rs
  core/domain/src/c.rs
  core/domain/src/cluster.rs
  core/domain/src/datastore/remote.rs
  core/domain/src/lib.rs
  core/domain/src/wasm.rs
  core/examples/client/src/main.rs
  core/examples/data-node/Cargo.toml
  core/examples/data-node/src/main.rs
  core/examples/domain-manager/Cargo.toml
  core/examples/domain-manager/src/main.rs
  core/examples/private_dialer.rs
  core/examples/private_receiver.rs
  core/examples/reconstruction-node/Cargo.toml
  core/examples/reconstruction-node/src/main.rs
  core/examples/relay.rs
  core/examples/relay/Cargo.toml
  core/examples/relay/src/main.rs
  core/include/Posemesh/Domain/Domain.h
  core/include/Posemesh/Networking/API.h
  core/networking/Cargo.toml
  core/networking/build.rs
  core/networking/src/binding_helper.rs
  core/networking/src/c.rs
  core/networking/src/c_compat_wasm.rs
  core/networking/src/client.rs
  core/networking/src/context.rs
  core/networking/src/event.rs
  core/networking/src/lib.rs
  core/networking/src/libp2p.rs
  core/scripts/Build-Library.ps1
  sdk/include/Posemesh/C/Config.h
  sdk/include/Posemesh/Config.hpp
  sdk/platform/Apple/include/Posemesh/Config.h
  sdk/platform/Apple/src/Config.mm
  sdk/platform/Apple/src/Config.swift
  sdk/platform/Web/Config.js
  sdk/platform/Web/examples/smoke-test/index.html
  sdk/platform/Web/src/Config.cpp
  sdk/src/C/Config.cpp
  sdk/src/Config.cpp
  sdk/src/Posemesh.cpp
Labels: bug, enhancement

#48 feat: add string gentool type
  sdk/gentool/README.md
  sdk/gentool/generator-c.js
  sdk/gentool/generator-cxx.js
  sdk/gentool/generator-objc.js
  sdk/gentool/util.js
  sdk/interface/Tester.json
  sdk/interface/Vector2.json
  sdk/interface/Vector3.json
  sdk/interface/Vector4.json
Labels: bug, enhancement

#49 feat: add Linux with AMD64 and ARM64 build
  .github/workflows/posemesh-sdk.yml
  core/README.md
  core/scripts/Build-Library.ps1
  sdk/README.md
  sdk/cmake/AddPlatformLibrary.cmake
  sdk/cmake/AddPlatformSources.cmake
  sdk/cmake/GetBuildDirectorySuffix.cmake
  sdk/cmake/GetRustTargetName.cmake
  sdk/cmake/LinkBaseLibrary.cmake
  sdk/cmake/LinkOpenCVLibrary.cmake
  sdk/cmake/LinkPlatformLibraries.cmake
  sdk/cmake/LinuxAArch64Toolchain.cmake
  sdk/cmake/PlatformCheck.cmake
  sdk/cmake/VSCodeToolchainSelector.cmake
  sdk/include/Posemesh/C/API.h
  sdk/include/Posemesh/QRDetection.hpp
  sdk/scripts/Build-Library.ps1
  sdk/src/C/QRDetection.cpp
  sdk/src/Posemesh.cpp
  third-party/scripts/Build-OpenCV-Library.ps1
Labels: enhancement

#51 fix: QRDetection refactor
  sdk/include/Posemesh/C/QRDetection.h
  sdk/include/Posemesh/QRDetection.hpp
  sdk/platform/Apple/include/Posemesh/PoseEstimation.h
  sdk/platform/Apple/include/Posemesh/QRDetection.h
  sdk/platform/Apple/src/PoseEstimation.swift
  sdk/platform/Apple/src/QRDetection.mm
  sdk/platform/Apple/src/QRDetection.swift
  sdk/platform/Web/QRDetection.js
  sdk/platform/Web/src/QRDetection.cpp
  sdk/src/C/QRDetection.cpp
  sdk/src/PoseEstimation.cpp
  sdk/src/QRDetection.cpp
Labels: enhancement

#52 feat: add more string types, class types, toString() operator support and _Nonnull Objective-C annotations
  sdk/gentool/README.md
  sdk/gentool/generator-c.js
  sdk/gentool/generator-cxx.js
  sdk/gentool/generator-js.js
  sdk/gentool/generator-objc.js
  sdk/gentool/generator-swift.js
  sdk/gentool/generator.js
  sdk/gentool/util.js
  sdk/interface/Tester.json
  sdk/interface/Vector2.json
  sdk/interface/Vector3.json
  sdk/interface/Vector4.json
  sdk/src/Vector2.cpp
  sdk/src/Vector3.cpp
  sdk/src/Vector4.cpp
Labels: enhancement

#53 fix: Linux linking
  sdk/cmake/LinkPlatformLibraries.cmake
  third-party/scripts/Build-OpenCV-Library.ps1
Labels: bug
