Repository aukilabs/posemesh, pull requests merged in 2025-06, with the labels that each got.

#93 chore: moved examples file & added new sample project
  research.md
  samples/example-projects.md
  sdk/example-projects.md
Labels: documentation

#91 feat: remove ITT & oneAPI (oneTBB) from OpenCV dependency (Linux build)
  third-party/scripts/Build-OpenCV-Library.ps1
Labels: bug, enhancement

#77 feat: add custom constructor and method support in API generator
  sdk/CMakeLists.txt
  sdk/gentool/README.md
  sdk/gentool/generator-c.js
  sdk/gentool/generator-cxx.js
  sdk/gentool/generator-js.js
  sdk/gentool/generator-objc.js
  sdk/gentool/generator-swift.js
  sdk/gentool/generator.js
  sdk/gentool/util.js
  sdk/interface/CompileTests/CompileTestClassShowcaseAllMemberPropTypes.json
  sdk/interface/CompileTests/CompileTestClassShowcaseAllStaticPropTypes.json
  sdk/interface/CompileTests/CompileTestFunctions.json
  sdk/interface/CompileTests/CompileTestMethods.json
  sdk/src/CompileTestFunctions.cpp
  sdk/src/CompileTestMethods.cpp
Labels: enhancement
