Repository aukilabs/posemesh, pull requests merged in 2025-01, with the labels that each got.

#25 fix: add privateKey and privateKeyPath options in psm::Config
  networking/examples/private_dialer.rs
  networking/examples/private_receiver.rs
  networking/examples/relay.rs
  networking/include/Posemesh/Networking/API.h
  networking/src/context.rs
  networking/src/network.rs
  sdk/CMakeLists.txt
  sdk/README.md
  sdk/include/Posemesh/C/Config.h
  sdk/include/Posemesh/Config.hpp
  sdk/platform/Apple/include/Posemesh/Config.h
  sdk/platform/Apple/src/Config.mm
  sdk/platform/Apple/src/Config.swift
  sdk/platform/Apple/src/Util.hpp
  sdk/platform/Apple/src/Util.mm
  sdk/platform/Web/API.js
  sdk/platform/Web/Config.js
  sdk/platform/Web/src/API.cpp
  sdk/platform/Web/src/Config.cpp
  sdk/platform/Web/transform-typescript-definitions.js
  sdk/src/C/Config.cpp
  sdk/src/Config.cpp
  sdk/src/Posemesh.cpp
Labels: bug, enhancement

#28 chore: added research.md
  research.md
Labels: documentation

#29 chore: added .clang-format with WebKit style
  .clang-format
Labels: enhancement

#30 chore: add Clang-Format support to CMake
  .clang-format
  .github/workflows/format-code.yml
  .github/workflows/posemesh-sdk.yml
  sdk/CMakeLists.txt
  sdk/cmake/FindClangFormat.cmake
  sdk/scripts/Format-Code.ps1
Labels: enhancement

#33 chore: added conventions section
  README.md
Labels: documentation

#34 feature: add Objective-C language generator
  sdk/gentool/README.md
  sdk/gentool/generator-cxx.js
  sdk/gentool/generator-objc.js
  sdk/gentool/generator-swift.js
  sdk/gentool/generator.js
  sdk/gentool/util.js
Labels: enhancement
