Repository aukilabs/posemesh, pull requests merged in 2025-04, with the labels that each got.

#58 build: run GitHub Actions workflow on PRs
  .github/workflows/posemesh-sdk.yml
Labels: cla-signed

#55 chore: reconstruction integration
  .github/workflows/posemesh-sdk.yml
  core/Cargo.lock
  core/Cargo.toml
  core/domain/Cargo.toml
  core/domain/examples/browser/.gitignore
  core/domain/examples/browser/README.md
  core/domain/examples/browser/index.html
  core/domain/examples/browser/main.js
  core/domain/examples/browser/package-lock.json
  core/domain/examples/browser/package.json
  core/domain/examples/browser/src/index.css
  core/domain/examples/browser/src/index.js
  core/domain/examples/browser/src/protobuf/domain_data.ts
  core/domain/examples/browser/src/protobuf/task.ts
  core/domain/examples/browser/tailwind.config.js
  core/domain/examples/browser/vite.config.js
  core/domain/examples/nodejs/index.js
  core/domain/examples/nodejs/package.json
  core/domain/src/c.rs
  core/domain/src/cluster.rs
  core/domain/src/datastore/common.rs
  core/domain/src/datastore/remote.rs
  core/domain/src/lib.rs
  core/domain/src/message.rs
  core/domain/src/protobuf/task.rs
  core/domain/src/spatial/mod.rs
  core/domain/src/spatial/reconstruction.rs
  core/domain/src/wasm.rs
  core/examples/client/src/main.rs
  core/examples/data-node/Cargo.toml
  core/examples/data-node/src/main.rs
  core/examples/domain-manager/Cargo.toml
  core/examples/domain-manager/src/main.rs
  core/examples/domain-manager/src/nodes_management.rs
  core/examples/domain-manager/src/tasks_management.rs
  core/examples/reconstruction-node/src/main.rs
  core/examples/relay/src/main.rs
  core/examples/test-concurrent/Cargo.toml
  core/examples/test-concurrent/src/main.rs
  core/networking/Cargo.toml
  core/networking/src/c.rs
  core/networking/src/c_compat_wasm.rs
  core/networking/src/client.rs
  core/networking/src/libp2p.rs
  core/protobuf/domain_data.proto
  core/protobuf/task.proto
  core/utils/Cargo.toml
  core/utils/src/lib.rs
Labels: cla-signed

#54 feat: add enum support to API generator tool & add toString() operator for matrices and quaternion types
  sdk/CMakeLists.txt
  sdk/enum/TestEnum.json
  sdk/gentool/README.md
  sdk/gentool/generator-c.js
  sdk/gentool/generator-cxx.js
  sdk/gentool/generator-enum.js
  sdk/gentool/generator-js.js
  sdk/gentool/generator-objc.js
  sdk/gentool/generator-swift.js
  sdk/gentool/generator.js
  sdk/gentool/util.js
  sdk/interface/Matrix2x2.json
  sdk/interface/Matrix3x3.json
  sdk/interface/Matrix4x4.json
  sdk/interface/Quaternion.json
  sdk/interface/Tester.json
  sdk/src/Matrix2x2.cpp
  sdk/src/Matrix3x3.cpp
  sdk/src/Matrix4x4.cpp
  sdk/src/Quaternion.cpp
Labels: bug, enhancement

#67 feat: ArUco support
  core/domain/src/protobuf/mod.rs
  sdk/CMakeLists.txt
  sdk/enum/ArucoMarkerFormat.json
  sdk/gentool/generator.js
  sdk/include/Posemesh/ArucoDetection.hpp
  sdk/include/Posemesh/C/ArucoDetection.h
  sdk/platform/Apple/include/Posemesh/ArucoDetection.h
  sdk/platform/Apple/src/ArucoDetection.mm
  sdk/platform/Apple/src/ArucoDetection.swift
  sdk/platform/Web/ArucoDetection.js
  sdk/platform/Web/examples/web_scanner/index-aruco.html
  sdk/platform/Web/src/ArucoDetection.cpp
  sdk/src/ArucoDetection.cpp
  sdk/src/C/ArucoDetection.cpp
Labels: enhancement

#62 feat: add fs and metadata stores
  core/Cargo.lock
  core/Cargo.toml
  core/domain/Cargo.toml
  core/domain/examples/browser/index.html
  core/domain/src/auth.rs
  core/domain/src/c.rs
  core/domain/src/cluster.rs
  core/domain/src/datastore/common.rs
  core/domain/src/datastore/fs.rs
  core/domain/src/datastore/metadata.rs
  core/domain/src/datastore/mod.rs
  core/domain/src/datastore/remote.rs
  core/domain/src/lib.rs
  core/domain/src/protobuf/domain_data.rs
  core/domain/src/wasm.rs
  core/examples/client/Cargo.toml
  core/examples/client/src/main.rs
  core/examples/data-node/Cargo.toml
  core/examples/data-node/src/main.rs
  core/examples/domain-manager/Cargo.toml
  core/examples/domain-manager/src/main.rs
  core/examples/domain-manager/src/nodes_management.rs
  core/examples/domain-manager/src/tasks_management.rs
  core/examples/relay/src/main.rs
  core/examples/test-concurrent/src/main.rs
  core/include/Posemesh/Domain/Domain.h
  core/networking/src/c.rs
  core/networking/src/c_compat_wasm.rs
  core/networking/src/client.rs
  core/networking/src/lib.rs
  core/networking/src/libp2p.rs
  core/protobuf/domain_data.proto
  core/utils/src/lib.rs
Labels: cla-signed

#66 feat: add array support to API generator tool
  sdk/enum/CompileTests/CompileTestExampleEnum.json
  sdk/enum/CompileTests/CompileTestExampleFlags.json
  sdk/enum/CompileTests/CompileTestExampleFlags2.json
  sdk/enum/TestEnum.json
  sdk/gentool/README.md
  sdk/gentool/generator-c.js
  sdk/gentool/generator-cxx.js
  sdk/gentool/generator-js.js
  sdk/gentool/generator-objc.js
  sdk/gentool/generator-swift.js
  sdk/gentool/generator.js
  sdk/gentool/shared.js
  sdk/gentool/util.js
  sdk/interface/CompileTests/CompileTestClassShowcaseAllMemberPropTypes.json
  sdk/interface/CompileTests/CompileTestClassShowcaseAllStaticPropTypes.json
  sdk/interface/CompileTests/CompileTestDummyClass.json
  sdk/interface/Tester.json
Labels: enhancement
